# Generated by Django 5.2.4 on 2025-07-22 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_phone_number_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_assets',
            field=models.BooleanField(default=False, verbose_name='can manage assets'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_categories',
            field=models.BooleanField(default=False, verbose_name='can manage categories'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_reports',
            field=models.BooleanField(default=False, verbose_name='can manage reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='can manage users'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False, verbose_name='can view audit logs'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='last login location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=20, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.ManyToManyField(related_name='permission_groups', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'permission group',
                'verbose_name_plural': 'permission groups',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='users.permissiongroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_permission_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user permission',
                'verbose_name_plural': 'user permissions',
                'unique_together': {('user', 'permission_group')},
            },
        ),
    ]
