# Generated by Django 5.2.4 on 2025-07-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_account_locked_until_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('password_change', 'Password Change'), ('account_locked', 'Account Locked'), ('account_activated', 'Account Activated'), ('account_deactivated', 'Account Deactivated'), ('profile_updated', 'Profile Updated')], max_length=20),
        ),
    ]
