# Generated by Django 5.2.4 on 2025-08-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_can_manage_assets_user_can_manage_categories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='permission_group',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_assets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_categories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_reports',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_manage_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_view_audit_logs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_location',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
