# Generated by Django 5.2.4 on 2025-08-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userpermission_permission_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Can manage users and their permissions'), ('can_manage_assets', 'Can manage assets'), ('can_manage_categories', 'Can manage asset categories'), ('can_manage_reports', 'Can generate and manage reports'), ('can_view_audit_logs', 'Can view audit logs')]},
        ),
    ]
