# Generated by Django 5.2.4 on 2025-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_accesslog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='browser_fingerprint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='logout_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together={('user', 'session_key', 'browser_fingerprint')},
        ),
    ]
