# Generated by Django 5.2.4 on 2025-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersession_browser_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_context',
            field=models.CharField(choices=[('web', 'Web Application'), ('admin', 'Django Admin'), ('api', 'API Access'), ('mobile', 'Mobile App')], default='web', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together={('user', 'session_key', 'browser_fingerprint', 'session_context')},
        ),
    ]
