# Generated by Django 5.2.4 on 2025-07-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usersession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='browser_fingerprint',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key', 'is_active'], name='user_sessio_session_b2102c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx'),
        ),
    ]
