# Generated by Django 5.2.4 on 2025-08-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options'),
        ('users', '0007_alter_usersession_unique_together_and_more'),
    ]

    operations = [
    ]
