# Generated by Django 5.2.4 on 2025-08-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20250826_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.CharField(default='roles_permissions_singleton', editable=False, max_length=64, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_permission_matrix',
            },
        ),
    ]
