# Generated by Django 5.1.14 on 2025-11-13 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_alter_approvalrequest_request_type'),
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retired_at',
            field=models.DateTimeField(blank=True, help_text='When user was retired/deactivated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='retired_by',
            field=models.ForeignKey(blank=True, help_text='Admin who retired this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRetirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for retirement (e.g., resignation, termination, transfer)')),
                ('asset_count', models.IntegerField(default=0, help_text='Number of assets to reassign')),
                ('status', models.CharField(choices=[('pending_asset_transfer', 'Pending Asset Transfer'), ('assets_transferred', 'Assets Transferred'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_asset_transfer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about retirement process')),
                ('company', models.ForeignKey(help_text='Company context for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, to='tenancy.company')),
                ('completed_by', models.ForeignKey(blank=True, help_text='Admin who completed retirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_retirements', to=settings.AUTH_USER_MODEL)),
                ('retired_by', models.ForeignKey(help_text='Admin who initiated retirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_retirements', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User being retired', on_delete=django.db.models.deletion.CASCADE, related_name='retirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Retirement',
                'verbose_name_plural': 'User Retirements',
                'db_table': 'user_retirements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='user_retire_company_ae3007_idx'), models.Index(fields=['user', 'created_at'], name='user_retire_user_id_0d169e_idx'), models.Index(fields=['status', 'created_at'], name='user_retire_status_827750_idx')],
            },
        ),
    ]
