# Generated by Django 5.2.4 on 2025-11-27 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_refactor_retirement_self_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When verification email was sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token for email verification', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email address verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_system_admin',
            field=models.BooleanField(default=False, help_text='Super admin (not tied to company)'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='User completed onboarding wizard'),
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='asset_count',
            field=models.IntegerField(default=0, help_text='Total number of assigned assets'),
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When retirement completed', null=True),
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Desired last working day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes from employee'),
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='reason',
            field=models.TextField(help_text='Detailed reason for retirement'),
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When request was submitted'),
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='requested_by',
            field=models.ForeignKey(help_text='Person who submitted request (usually self)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_retirement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userretirement',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('asset_handover', 'Asset Handover'), ('final_review', 'Final Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=50),
        ),
    ]
