# Generated by Django 5.1.14 on 2025-12-01 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_remove_duplicatedetection_asset1_and_more'),
        ('users', '0016_add_user_initiated_transfers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assettransferselection',
            name='unique_asset_per_transfer_request',
        ),
        migrations.RemoveIndex(
            model_name='userbranchtransferrequest',
            name='user_transfer_init_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbranchtransferrequest',
            name='user_transfer_mgr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assettransferselection',
            new_name='asset_trans_transfe_88f7ac_idx',
            old_name='asset_sel_request_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assettransferselection',
            new_name='asset_trans_transfe_920788_idx',
            old_name='asset_sel_request_selected_idx',
        ),
        migrations.RenameIndex(
            model_name='assettransferselection',
            new_name='asset_trans_asset_i_f5ac46_idx',
            old_name='asset_sel_asset_idx',
        ),
        migrations.RenameIndex(
            model_name='assettransferselection',
            new_name='asset_trans_company_24570d_idx',
            old_name='asset_sel_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userbranchtransferrequest',
            new_name='user_branch_company_cf8036_idx',
            old_name='user_branch_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userbranchtransferrequest',
            new_name='user_branch_user_id_4e6df8_idx',
            old_name='user_branch_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userbranchtransferrequest',
            new_name='user_branch_to_bran_d48dee_idx',
            old_name='user_branch_to_branch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userbranchtransferrequest',
            new_name='user_branch_initiat_b1d71d_idx',
            old_name='user_branch_initiated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='userbranchtransferrequest',
            new_name='user_branch_status_aabdca_idx',
            old_name='user_branch_status_initiated_idx',
        ),
        migrations.AlterField(
            model_name='userbranchtransferrequest',
            name='approval_decision_at',
            field=models.DateTimeField(blank=True, help_text='When admin made approval decision', null=True),
        ),
        migrations.AlterField(
            model_name='userbranchtransferrequest',
            name='approval_reason',
            field=models.TextField(blank=True, help_text='Admin approval decision reason'),
        ),
        migrations.AlterField(
            model_name='userbranchtransferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbranchtransferrequest',
            name='initiated_by',
            field=models.ForeignKey(help_text='Admin/Manager/User who initiated transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_user_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assettransferselection',
            unique_together={('transfer_request', 'asset')},
        ),
    ]
