# Generated by Django 5.2.4 on 2025-10-25 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_add_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when asset was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_method',
            field=models.CharField(blank=True, choices=[('sell', 'Sell'), ('donate', 'Donate'), ('scrap', 'Scrap'), ('recycle', 'Recycle'), ('transfer', 'Transfer to another entity')], help_text='Method of disposal', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_known_location',
            field=models.CharField(blank=True, help_text='Last known location of asset', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='loss_details',
            field=models.TextField(blank=True, help_text='Detailed description of loss circumstances'),
        ),
        migrations.AddField(
            model_name='asset',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('lost', 'Lost/Misplaced'), ('stolen', 'Stolen'), ('damaged_beyond_repair', 'Damaged Beyond Repair')], help_text='Reason for loss', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='lost_at',
            field=models.DateField(blank=True, help_text='Date when asset was reported lost/stolen', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lost_by',
            field=models.ForeignKey(blank=True, help_text='User who reported the loss', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lost_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='permanent_deletion_date',
            field=models.DateField(blank=True, help_text='Date for permanent deletion (30 days after soft delete)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='police_report_number',
            field=models.CharField(blank=True, help_text='Police report number (if stolen)', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='reactivated_at',
            field=models.DateField(blank=True, help_text='Date when retired asset was reactivated', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='reactivated_by',
            field=models.ForeignKey(blank=True, help_text='User who reactivated the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivated_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='reactivation_reason',
            field=models.TextField(blank=True, help_text='Reason for reactivation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='recovered_at',
            field=models.DateField(blank=True, help_text='Date when lost asset was recovered', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='recovered_by',
            field=models.ForeignKey(blank=True, help_text='User who recovered the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovered_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='recovery_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], help_text='Condition of asset when recovered', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='recovery_notes',
            field=models.TextField(blank=True, help_text='Notes about asset recovery'),
        ),
        migrations.AddField(
            model_name='asset',
            name='retired_at',
            field=models.DateField(blank=True, help_text='Date when asset was retired', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='retired_by',
            field=models.ForeignKey(blank=True, help_text='User who retired the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='retirement_reason',
            field=models.TextField(blank=True, help_text='Reason for retirement'),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated salvage/resale value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status_change_reason',
            field=models.TextField(blank=True, help_text='Reason for status change'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last status change', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who last changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_status_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
