# Generated by Django 5.2.4 on 2025-07-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict, help_text='JSON schema for dynamic fields (auto-managed)'),
        ),
        migrations.CreateModel(
            name='AssetCategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Field key (e.g., serial_number)', max_length=50)),
                ('label', models.CharField(help_text='Field label (e.g., Serial Number)', max_length=100)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=20)),
                ('required', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='assets.assetcategory')),
            ],
            options={
                'verbose_name': 'Dynamic Field',
                'verbose_name_plural': 'Dynamic Fields',
                'unique_together': {('category', 'key')},
            },
        ),
    ]
