# Generated by Django 5.2.4 on 2025-07-08 14:49

import uuid
from django.db import migrations, models

def populate_uuids(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    for asset in Asset.objects.all():
        if not asset.uuid:
            asset.uuid = uuid.uuid4()
            asset.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetcategory_dynamic_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),
    ]
