# Generated by Django 5.2.4 on 2025-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_exportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('lost', 'Lost'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
    ]
