# Generated by Django 5.2.4 on 2025-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight Line')], default='straight_line', help_text='Depreciation method', max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date of purchase/acquisition', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial purchase value for depreciation', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, help_text='Useful life in years for depreciation', null=True),
        ),
    ]
