# Generated by Django 5.2.4 on 2025-10-03 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_company_branch'),
        ('tenancy', '0005_rename_tenancy_ale_recipi_c8d328_idx_tenancy_ale_recipie_654015_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportlog',
            name='filters',
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending_receiver', 'Pending receiver approval'), ('receiver_approved', 'Receiver approved'), ('receiver_rejected', 'Receiver rejected'), ('awaiting_admin', 'Awaiting admin review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_receiver', max_length=32)),
                ('receiver_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True)),
                ('receiver_comment', models.TextField(blank=True)),
                ('receiver_decided_at', models.DateTimeField(blank=True, null=True)),
                ('admin_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('admin_decided_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assets.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_transfers', to='tenancy.company')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_asset_transfers', to='tenancy.branch')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_asset_transfers', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_asset_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_asset_transfers', to='tenancy.branch')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_asset_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'state'], name='asset_tr_company_state'), models.Index(fields=['to_user', 'state'], name='asset_tr_to_user_state'), models.Index(fields=['asset', 'state'], name='asset_tr_asset_state')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state__in', ['pending_receiver', 'receiver_approved', 'awaiting_admin'])), fields=('asset',), name='unique_active_transfer_per_asset')],
            },
        ),
    ]
