# Generated by Django 5.2.4 on 2025-10-07 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_remove_exportlog_filters_assettransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who approved the transfer when completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Business justification provided when the transfer was initiated.'),
        ),
    ]
