# Generated by Django 5.2.4 on 2025-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_assetcategory_company_assetcategoryfield_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
