# Generated by Django 5.2.4 on 2025-10-11 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_assetcategory_name'),
        ('tenancy', '0008_approvalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, help_text='Date of last completed maintenance', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_enabled',
            field=models.BooleanField(default=False, help_text='Enable maintenance tracking for this asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maintenance interval in days (e.g., 90 for quarterly)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_notes',
            field=models.TextField(blank=True, help_text='General maintenance notes and requirements'),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_maintenance_date',
            field=models.DateField(blank=True, help_text='Scheduled date for next maintenance', null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_for', models.DateField(help_text='Planned maintenance date.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='tenancy.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
                'indexes': [models.Index(fields=['company', 'scheduled_for'], name='maint_company_sched_idx'), models.Index(fields=['company', 'status'], name='maint_company_status_idx'), models.Index(fields=['asset', 'status'], name='maint_asset_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='maintenance_cost_non_negative')],
            },
        ),
    ]
