# Generated by Django 5.2.4 on 2025-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_asset_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
