# Generated by Django 5.2.4 on 2025-11-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_normalize_asset_status'),
        ('assets', '0017_fix_transferred_assets'),
    ]

    operations = [
    ]
