# Generated by Django 5.2.4 on 2025-11-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_normalize_category_field_keys'),
        ('assets', '0018_merge_20251110_1300'),
    ]

    operations = [
    ]
