# Generated by Django 5.1.14 on 2025-11-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_merge_20251111_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategoryfield',
            name='is_unique',
            field=models.BooleanField(default=False, help_text='If true, this field value must be unique across all assets in this category within the company. Example: Serial numbers for computers, VIN for vehicles, asset tags for furniture.'),
        ),
    ]
