# Generated by Django 5.1.14 on 2025-11-19 09:16

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    """
    WORLD-CLASS DUPLICATE DETECTION IMPLEMENTATION
    
    This migration implements Layer 1 of our duplicate detection system:
    - Hard unique constraints at database level (strongest protection)
    - Multi-tenant scoping (company-level uniqueness only)
    - Conditional constraints (allows NULL values but enforces uniqueness when present)
    
    Inspired by:
    - ServiceNow ITAM: CI attribute uniqueness
    - IBM Maximo: Asset specification constraints  
    - SAP EAM: Equipment identification fields
    """

    dependencies = [
        ('assets', '0022_remove_depreciation_fields'),
    ]

    operations = [
        # Add the three core duplicate detection fields
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                help_text='Manufacturer serial number (unique per company)'
            ),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                help_text='Internal asset tag/identifier (unique per company)'
            ),
        ),
        migrations.AddField(
            model_name='asset',
            name='qr_string',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=255,
                help_text='QR code string identifier (unique per company)'
            ),
        ),
        
        # Add database indexes for performance
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'serial_number'], name='asset_company_serial'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'asset_tag'], name='asset_company_tag'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'qr_string'], name='asset_company_qr'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'status'], name='asset_company_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company', 'category'], name='asset_company_category'),
        ),
        
        # Add conditional unique constraints (database-level duplicate prevention)
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(
                fields=['company', 'serial_number'],
                condition=Q(serial_number__isnull=False) & ~Q(serial_number=''),
                name='unique_serial_per_company'
            ),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(
                fields=['company', 'asset_tag'],
                condition=Q(asset_tag__isnull=False) & ~Q(asset_tag=''),
                name='unique_tag_per_company'
            ),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(
                fields=['company', 'qr_string'],
                condition=Q(qr_string__isnull=False) & ~Q(qr_string=''),
                name='unique_qr_per_company'
            ),
        ),
    ]
