# Generated by Django 5.2.4 on 2025-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_add_hard_unique_constraints_for_duplicates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicatedetection',
            name='asset1',
        ),
        migrations.RemoveField(
            model_name='duplicatedetection',
            name='asset2',
        ),
        migrations.RemoveField(
            model_name='duplicatedetection',
            name='company',
        ),
        migrations.RemoveField(
            model_name='duplicatedetection',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='duplicatedetection',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='duplicatedetection',
            name='rules_triggered',
        ),
        migrations.AlterUniqueTogether(
            name='duplicatedetectionrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='duplicatedetectionrule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='duplicatedetectionrule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='duplicatedetectionrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='duplicatescanhistory',
            name='rules_applied',
        ),
        migrations.RemoveField(
            model_name='duplicatescanhistory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='duplicatescanhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='duplicatescanhistory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='duplicatescanhistory',
            name='initiated_by',
        ),
        migrations.AlterField(
            model_name='asset',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code image file', null=True, upload_to='qr_codes/'),
        ),
        migrations.DeleteModel(
            name='AssetMergeHistory',
        ),
        migrations.DeleteModel(
            name='DuplicateDetection',
        ),
        migrations.DeleteModel(
            name='DuplicateDetectionRule',
        ),
        migrations.DeleteModel(
            name='DuplicateScanHistory',
        ),
    ]
