# Generated by Django 5.2.1 on 2026-06-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_remove_duplicatedetection_asset1_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='customer_reference',
            field=models.ForeignKey(blank=True, help_text='Synced customer linked to this asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='integrations.externalcustomerreference'),
        ),
    ]
