# Generated by Django 5.2.4 on 2025-11-27 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0011_alter_approvalrequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', help_text='Subscription plan', max_length=20)),
                ('trial_ends_at', models.DateField(blank=True, help_text='Trial period end date (14 days from signup)', null=True)),
                ('billing_email', models.EmailField(help_text='Email for billing communications', max_length=254)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='trial', max_length=20)),
                ('payment_provider', models.CharField(blank=True, help_text="Payment provider (e.g., 'stripe', 'paypal', 'mpesa') - to be configured", max_length=50)),
                ('payment_customer_id', models.CharField(blank=True, help_text='Customer ID in payment provider system', max_length=100)),
                ('payment_subscription_id', models.CharField(blank=True, help_text='Subscription ID in payment provider system', max_length=100)),
                ('max_users', models.IntegerField(default=5, help_text='Maximum number of users allowed')),
                ('max_assets', models.IntegerField(default=100, help_text='Maximum number of assets allowed')),
                ('max_storage_mb', models.IntegerField(default=1000, help_text='Maximum storage in MB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(help_text='Company profile', on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='tenancy.company')),
            ],
            options={
                'verbose_name': 'Company Registration',
                'verbose_name_plural': 'Company Registrations',
                'db_table': 'company_registrations',
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_details_completed', models.BooleanField(default=False, help_text='Step 1: Company profile filled')),
                ('team_invited', models.BooleanField(default=False, help_text='Step 2: Team members invited')),
                ('tour_completed', models.BooleanField(default=False, help_text='Step 3: Product tour completed')),
                ('first_asset_created', models.BooleanField(default=False, help_text='Bonus: First asset registered')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When onboarding was fully completed', null=True)),
                ('current_step', models.IntegerField(default=1, help_text='Current step number (1-3)')),
                ('skipped', models.BooleanField(default=False, help_text="User clicked 'Skip Onboarding'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User completing onboarding', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progress Records',
                'db_table': 'onboarding_progress',
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of invitee', max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], help_text='Role to assign upon acceptance', max_length=20)),
                ('invitation_token', models.CharField(db_index=True, editable=False, help_text='Secure token for invitation link', max_length=100, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expires 7 days after sending')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch to assign user to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenancy.branch')),
                ('company', models.ForeignKey(help_text='Company the user is invited to join', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenancy.company')),
                ('invited_by', models.ForeignKey(blank=True, help_text='Admin who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Invitation',
                'verbose_name_plural': 'User Invitations',
                'db_table': 'user_invitations',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='invitation_company_status_idx'), models.Index(fields=['email', 'status'], name='invitation_email_status_idx')],
            },
        ),
    ]
