# Generated by Django 5.2.4 on 2025-10-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_alert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='tenancy_ale_recipie_654015_idx',
            old_name='tenancy_ale_recipi_c8d328_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='tenancy_ale_company_b5013e_idx',
            old_name='tenancy_ale_compan_ad4bec_idx',
        ),
    ]
