# Generated by Django 5.2.4 on 2025-10-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_rename_tenancy_ale_recipi_c8d328_idx_tenancy_ale_recipie_654015_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'is_active'], name='branch_company_active_idx'),
        ),
    ]
