# Generated by Django 5.2.4 on 2025-10-10 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_branch_is_active_branch_branch_company_active_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Primary manager responsible for this branch', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned the current manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
