# Generated by Django 5.2.4 on 2025-10-10 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_add_branch_manager_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('asset_transfer', 'Asset Transfer'), ('asset_maintenance', 'Asset Maintenance'), ('asset_disposal', 'Asset Disposal'), ('user_access', 'User Access Request'), ('budget', 'Budget Approval'), ('custom', 'Custom Request')], help_text='Type of approval request', max_length=50)),
                ('title', models.CharField(help_text='Brief title of the request', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data specific to request type')),
                ('deadline', models.DateTimeField(blank=True, help_text='Deadline for approval decision', null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Manager/admin assigned to review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(help_text='Branch where request originated', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='tenancy.company')),
                ('requested_by', models.ForeignKey(help_text='User who created the request', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'created_at'], name='tenancy_app_company_9a6517_idx'), models.Index(fields=['branch', 'status'], name='tenancy_app_branch__d1583e_idx'), models.Index(fields=['assigned_to', 'status'], name='tenancy_app_assigne_7b0581_idx')],
            },
        ),
    ]
