# Generated by Django 5.2.4 on 2025-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_approvalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('asset_creation', 'Asset Creation'), ('asset_transfer', 'Asset Transfer'), ('asset_maintenance', 'Asset Maintenance'), ('asset_disposal', 'Asset Disposal'), ('user_access', 'User Access Request'), ('budget', 'Budget Approval'), ('custom', 'Custom Request')], help_text='Type of approval request', max_length=50),
        ),
    ]
