# Generated by Django 5.2.4 on 2025-10-20 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_add_asset_creation_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTenancyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_data_isolation', models.BooleanField(default=True, editable=False, help_text='Ensures complete data separation between companies (Always enabled for security)')),
                ('branch_level_access', models.BooleanField(default=True, help_text="Restrict managers and users to their assigned branches only. When enabled, users can only view/manage assets in branches they're assigned to. Admins always have company-wide access.")),
                ('allow_cross_branch_transfers', models.BooleanField(default=True, help_text='Enable asset transfers between different branches within the same company. When disabled, assets can only be transferred within the same branch.')),
                ('require_transfer_approval', models.BooleanField(default=True, help_text='All asset transfers must go through the approval workflow (Receiver → Admin). When disabled, transfers are completed immediately without approval.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(help_text='Company this policy applies to', on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_policy', to='tenancy.company')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last admin who modified this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multi-Tenancy Policy',
                'verbose_name_plural': 'Multi-Tenancy Policies',
                'ordering': ['company__name'],
                'indexes': [models.Index(fields=['company'], name='policy_company_idx')],
            },
        ),
    ]
