# Generated by Django 5.2.4 on 2025-11-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_multitenancypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('asset_creation', 'Asset Creation'), ('asset_disposal', 'Asset Disposal')], help_text='Type of approval request', max_length=50),
        ),
    ]
