# Generated by Django 4.2.16 on 2026-05-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_alter_approvalrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('asset_creation', 'Asset Creation'), ('asset_disposal', 'Asset Disposal'), ('asset_transfer', 'Asset Transfer'), ('asset_maintenance', 'Asset Maintenance'), ('user_access', 'User Access Request'), ('budget', 'Budget Approval'), ('custom', 'Custom Request')], help_text='Type of approval request', max_length=50),
        ),
    ]
