# Generated by Django 5.2.4 on 2025-07-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_depreciation_method_asset_purchase_date_and_more'),
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured metadata for advanced filtering/grouping'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='related_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_audit_logs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('move', 'Move'), ('delete', 'Delete'), ('create', 'Create'), ('add', 'Add'), ('assign', 'Assign/Transfer'), ('scan', 'Scan'), ('maintenance', 'Maintenance'), ('error', 'Error'), ('login', 'Login'), ('logout', 'Logout')], max_length=20),
        ),
    ]
