# Generated by Django 5.2.4 on 2025-10-07 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_assettransfer_approved_by_assettransfer_reason'),
        ('audit', '0003_auditlog_metadata_auditlog_related_asset_and_more'),
        ('tenancy', '0005_rename_tenancy_ale_recipi_c8d328_idx_tenancy_ale_recipie_654015_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch context when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Owning company for tenancy scoping.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenancy.company'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'branch', 'timestamp'], name='audit_company_branch_ts'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_action_ts'),
        ),
    ]
