# Generated by Django 5.2.4 on 2025-11-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_status_change_tracking'),
        ('audit', '0004_alter_auditlog_options_auditlog_branch_and_more'),
        ('tenancy', '0011_alter_approvalrequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('SESSION_EXPIRED', 'Session Expired'), ('ASSET_CREATED', 'Asset Created'), ('ASSET_UPDATED', 'Asset Updated'), ('ASSET_DELETED', 'Asset Deleted'), ('ASSET_TRANSFERRED', 'Asset Transferred'), ('ASSET_STATUS_CHANGED', 'Asset Status Changed'), ('SETTINGS_CHANGED', 'Settings Changed'), ('PERMISSION_CHANGED', 'Permission Changed'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_RESTORED', 'Backup Restored')], db_index=True, help_text='Type of event/action', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', help_text='Severity level of the event', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the event')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('company', models.ForeignKey(help_text='Company context for multi-tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='tenancy.company')),
                ('related_asset', models.ForeignKey(blank=True, help_text='Asset related to the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='assets.asset')),
                ('related_user', models.ForeignKey(blank=True, help_text='User affected by the action (e.g., user being edited)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_audit_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'timestamp'], name='audit_evt_company_ts'), models.Index(fields=['action', 'timestamp'], name='audit_evt_action_ts'), models.Index(fields=['user', 'timestamp'], name='audit_evt_user_ts'), models.Index(fields=['severity', 'timestamp'], name='audit_evt_severity_ts')],
            },
        ),
    ]
