# Generated by Django 5.1.14 on 2025-11-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('move', 'Move'), ('delete', 'Delete'), ('create', 'Create'), ('add', 'Add'), ('assign', 'Assign/Transfer'), ('scan', 'Scan'), ('maintenance', 'Maintenance'), ('error', 'Error'), ('login', 'Login'), ('logout', 'Logout')], max_length=50),
        ),
    ]
