"""
Django settings for assetms project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if available
load_dotenv(BASE_DIR / '.env')

def env_list(name: str, default: str = "") -> list[str]:
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]

def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY not set! Define it in your environment (.env or Railway variables).")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "10.10.10.254,localhost,127.0.0.1")

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

# CSRF Settings for Enterprise Security
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://assetms-production.up.railway.app',  # explicit trusted origin for Railway deployment
] + env_list("CSRF_TRUSTED_ORIGINS")

# WORLD-CLASS: CSRF Cookie Configuration
# Following Django's official documentation for AJAX requests
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)  # Only send over HTTPS in production
CSRF_COOKIE_HTTPONLY = False  # CRITICAL: Must be False so JavaScript can read the token
CSRF_COOKIE_SAMESITE = 'Lax'  # Prevents CSRF attacks while allowing normal navigation
CSRF_USE_SESSIONS = False  # Use cookies for better cross-tab compatibility
CSRF_COOKIE_AGE = 31449600  # 1 year (standard Django default)

# IMPORTANT: CSRF_COOKIE_HTTPONLY must be False for AJAX requests
# This allows JavaScript to read the csrftoken cookie and include it in X-CSRFToken header
# The token is still secure because:
# 1. It's validated by Django's CsrfViewMiddleware
# 2. It's tied to the user's session
# 3. It changes on login/logout
# 4. SameSite=Lax prevents cross-site attacks


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'import_export',
    # Project apps
    'tenancy',
    'users',
    'accounts',  # User registration, onboarding, invitations
    'system_admin',  # System-level administration
    'assets',
    'categories',
    'audit',
    'reports',
    'settings',
    'integrations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'assetms.middleware.CustomCSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # add whitenoise near top
    # REMOVED: Session isolation middlewares (caused Django admin login failures)
    # Reason: Modifying settings.SESSION_COOKIE_NAME dynamically breaks session handling
    # Solution: Use single session with Django's built-in permission system
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.force_password_change_middleware.ForcePasswordChangeMiddleware',
    'users.csrf_middleware.EnterpriseCSRFMiddleware',
    'users.login_security_middleware.LoginPageSecurityMiddleware',
    'users.concurrent_session_middleware.EnterpriseConcurrentSessionMiddleware',
    'users.concurrent_session_middleware.SessionTimeoutMiddleware',
    'users.admin_isolation_middleware.AdminSessionIsolationMiddleware',
    'users.session_middleware.LoginLogoutMiddleware',
    'tenancy.middleware.TenancyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.PerformanceMonitoringMiddleware',
    'users.middleware.APIErrorHandlingMiddleware',
]

ROOT_URLCONF = 'assetms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.user_view_data',
                'tenancy.context_processors.tenancy_context',
                'accounts.context_processors.trial_status',
                'accounts.context_processors.company_limits',
            ],
        },
    },
]

WSGI_APPLICATION = 'assetms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
def _env(name: str, default: str | None = None):
    return os.getenv(name, default)

# Database - use DATABASE_URL for production (Railway will provide)
DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
        ssl_require=os.environ.get("DB_SSL", "False") == "True",
    )
}

# SQLite-specific optimizations to reduce lock contention
if 'sqlite' in DATABASES['default']['ENGINE']:
    DATABASES['default']['OPTIONS'] = {
        'timeout': 20,  # Increase timeout from default 5s to 20s
        'check_same_thread': False,  # Allow multi-threaded access
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [str(BASE_DIR / "static")]

if DEBUG or TESTING:
    STATICFILES_BACKEND = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_BACKEND = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise settings
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True
WHITENOISE_STATIC_PREFIX = '/static/'

# STORAGES for Django 4.2+
STORAGES = {
    "default": {
        "BACKEND": "assetms.storage_backends.MultiStorageBackend",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}

# Media files (uploads) - Multi-storage with Cloudinary primary
USE_CLOUDINARY = os.environ.get('USE_CLOUDINARY', 'False').lower() == 'true'
USE_IMAGEKIT = os.environ.get('USE_IMAGEKIT', 'False').lower() == 'true'
USE_B2 = os.environ.get('USE_B2', 'False').lower() == 'true'

# Backward compatibility

# Cloudinary Configuration (Primary)
if USE_CLOUDINARY:
    CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME')
    CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY')
    CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET')
    MEDIA_URL = f"https://res.cloudinary.com/{CLOUDINARY_CLOUD_NAME}/image/upload/"

# ImageKit Configuration (Fallback)
elif USE_IMAGEKIT:
    IMAGEKIT_PRIVATE_KEY = os.environ.get('IMAGEKIT_PRIVATE_KEY')
    IMAGEKIT_PUBLIC_KEY = os.environ.get('IMAGEKIT_PUBLIC_KEY')
    IMAGEKIT_URL_ENDPOINT = os.environ.get('IMAGEKIT_URL_ENDPOINT', '')
    MEDIA_URL = IMAGEKIT_URL_ENDPOINT.rstrip('/') + '/' if IMAGEKIT_URL_ENDPOINT else '/media/'

# Backblaze B2 Configuration (Fallback)
elif USE_B2:
    # B2 Settings for fallback
    AWS_ACCESS_KEY_ID = os.environ.get('B2_APPLICATION_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('B2_APPLICATION_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('B2_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('B2_BUCKET_REGION', 'us-east-005')
    AWS_S3_ENDPOINT_URL = f"https://s3.{AWS_S3_REGION_NAME}.backblazeb2.com"
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
    MEDIA_URL = f"https://f002.backblazeb2.com/file/{os.environ.get('B2_BUCKET_NAME', '')}/"

else:
    # Local storage fallback
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
    STATICFILES_DIRS.append((str(BASE_DIR / "media"), "media"))
    WHITENOISE_DIRECTORIES = [(str(BASE_DIR / "media"), "/media/")]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Custom authentication backend for email-based login
# Supports both email and username for backward compatibility
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',  # Custom: email or username login
    'django.contrib.auth.backends.ModelBackend',  # Fallback to default
]

# Ensure all login-required redirects use the branded login page
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = '/dashboard/'

# Enterprise Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", 31536000)) if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Disable Django's default CSP to use our custom one
SECURE_CONTENT_SECURITY_POLICY = None
CSP_DEFAULT_SRC = None
CSP_IMG_SRC = None
CSP_SCRIPT_SRC = None
CSP_STYLE_SRC = None

# WORLD-CLASS: Session Security
# UPDATED APPROACH: Single session for both admin and regular dashboard
# Following best practices from ServiceNow ITAM, IBM Maximo, SAP EAM
#
# Previous approach (separate sessions) had critical flaws:
# - Modifying settings.SESSION_COOKIE_NAME dynamically broke Django admin login
# - Multi-threaded environments caused race conditions
# - Session handling became unpredictable
#
# Current approach (single session):
# - User logs in once, can access both admin and regular dashboard
# - Django's built-in permission system handles access control
# - Simpler, more reliable, follows Django best practices
# - No session isolation needed - unified authentication is better!

SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified (performance optimization)

# Permission Cache Settings
PERMISSION_CACHE_TIMEOUT = 3600

# ==========================
# Logging Configuration
# ==========================
# Railway & most cloud platforms do not persist files.
# So in production we log to console only.
# In local dev (DEBUG=True), we also log to a local file for debugging.

LOG_DIR = BASE_DIR / "logs"
if DEBUG:
    os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "django.log") if DEBUG else os.devnull,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"] if not DEBUG else ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}


# Email configuration
# Defaults to console backend in DEBUG. Configure environment variables for real SMTP in production.
EMAIL_BACKEND = _env('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = _env('EMAIL_HOST', '')
EMAIL_PORT = int(_env('EMAIL_PORT', '587'))
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = _env('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = _env('EMAIL_USE_SSL', 'False').lower() == 'true'
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', 'AssetMS <no-reply@assetms.local>')

# Custom CSP middleware handles Content Security Policy
# See assetms/middleware.py for CSP configuration

# ==========================
# Celery Configuration
# ==========================
# Development: Use EAGER mode (tasks execute synchronously, no worker/broker needed)
# Production: Use Redis broker for true async execution
if DEBUG:
    # EAGER mode: Tasks execute immediately in the same process
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'django-db'
    print("Celery EAGER mode enabled - tasks execute synchronously (no worker needed)")
else:
    # Production: Use Redis broker for true async execution
    _broker_url = os.environ.get('CELERY_BROKER_URL') or os.environ.get('REDIS_URL')
    if _broker_url:
        CELERY_TASK_ALWAYS_EAGER = False
        CELERY_BROKER_URL = _broker_url
        CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')
    else:
        CELERY_TASK_ALWAYS_EAGER = True
        CELERY_TASK_EAGER_PROPAGATES = True
        CELERY_BROKER_URL = 'memory://'
        CELERY_RESULT_BACKEND = 'django-db'

# Celery Task Settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task execution settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
CELERY_TASK_ACKS_LATE = True  # Task acknowledged after execution
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # One task at a time per worker

# Result backend settings
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_RESULT_PERSISTENT = True  # Persist results to backend

# Task retry settings
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # Retry after 60 seconds
CELERY_TASK_MAX_RETRIES = 3  # Maximum 3 retries

# Worker settings
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after 1000 tasks
CELERY_WORKER_DISABLE_RATE_LIMITS = False  # Enable rate limiting

# Monitoring
CELERY_SEND_TASK_SENT_EVENT = True  # Send task-sent events
CELERY_SEND_TASK_ERROR_EMAILS = not DEBUG  # Email on task errors in production

# Security
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Reject task if worker dies
CELERY_TASK_IGNORE_RESULT = False  # Store task results

EXTERNAL_CUSTOMER_SYNC_TIMEOUT_SECONDS = int(os.environ.get('EXTERNAL_CUSTOMER_SYNC_TIMEOUT_SECONDS', '15'))

# Django Celery Beat (Database-backed periodic tasks)
INSTALLED_APPS += [
    'django_celery_beat',
    'django_celery_results',
]

# Store task results in Django database
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'




