"""
Django settings for assetms project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if available
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY not set! Define it in your environment (.env or Railway variables).")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# include your Railway app domain in the default ALLOWED_HOSTS fallback
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# CSRF Settings for Enterprise Security
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://assetms-production.up.railway.app',  # explicit trusted origin for Railway deployment
]



CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'import_export',
    # Project apps
    'users',
    'assets',
    'categories',
    'audit',
    'reports',
    'settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'assetms.middleware.CustomCSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # add whitenoise near top
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.force_password_change_middleware.ForcePasswordChangeMiddleware',
    'users.csrf_middleware.EnterpriseCSRFMiddleware',
    'users.login_security_middleware.LoginPageSecurityMiddleware',
    'users.concurrent_session_middleware.EnterpriseConcurrentSessionMiddleware',
    'users.concurrent_session_middleware.SessionTimeoutMiddleware',
    'users.admin_isolation_middleware.AdminSessionIsolationMiddleware',
    'users.session_middleware.LoginLogoutMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.PerformanceMonitoringMiddleware',
    'users.middleware.APIErrorHandlingMiddleware',
]

ROOT_URLCONF = 'assetms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.user_view_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'assetms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _env(name: str, default: str | None = None):
    return os.getenv(name, default)

# Database - use DATABASE_URL for production (Railway will provide)
DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
        ssl_require=os.environ.get("DB_SSL", "False") == "True",
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [str(BASE_DIR / "static")]

# WhiteNoise: compressed static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Configure WhiteNoise to serve media files in production
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True
WHITENOISE_STATIC_PREFIX = '/static/'

# Media files (uploads) - Multi-storage with ImageKit primary, B2 fallback
USE_IMAGEKIT = os.environ.get('USE_IMAGEKIT', 'False').lower() == 'true'
USE_B2 = os.environ.get('USE_B2', 'False').lower() == 'true'

# Multi-storage backend
DEFAULT_FILE_STORAGE = 'assetms.storage_backends.MultiStorageBackend'

# ImageKit Configuration (Primary)
if USE_IMAGEKIT:
    IMAGEKIT_PRIVATE_KEY = os.environ.get('IMAGEKIT_PRIVATE_KEY')
    IMAGEKIT_PUBLIC_KEY = os.environ.get('IMAGEKIT_PUBLIC_KEY')
    IMAGEKIT_URL_ENDPOINT = os.environ.get('IMAGEKIT_URL_ENDPOINT', '')
    MEDIA_URL = IMAGEKIT_URL_ENDPOINT.rstrip('/') + '/' if IMAGEKIT_URL_ENDPOINT else '/media/'

# Backblaze B2 Configuration (Fallback)
elif USE_B2:
    # B2 Settings for fallback
    AWS_ACCESS_KEY_ID = os.environ.get('B2_APPLICATION_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('B2_APPLICATION_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('B2_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('B2_BUCKET_REGION', 'us-east-005')
    AWS_S3_ENDPOINT_URL = f"https://s3.{AWS_S3_REGION_NAME}.backblazeb2.com"
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
    MEDIA_URL = f"https://f002.backblazeb2.com/file/{os.environ.get('B2_BUCKET_NAME', '')}/"

else:
    # Local storage fallback
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
    STATICFILES_DIRS.append((str(BASE_DIR / "media"), "media"))
    WHITENOISE_DIRECTORIES = [(str(BASE_DIR / "media"), "/media/")]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Ensure all login-required redirects use the branded login page
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = '/dashboard/'

# Enterprise Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", 31536000)) if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Disable Django's default CSP to use our custom one
SECURE_CONTENT_SECURITY_POLICY = None

# Session Security
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # 1 hour

# Permission Cache Settings
PERMISSION_CACHE_TIMEOUT = 3600

# ==========================
# Logging Configuration
# ==========================
# Railway & most cloud platforms do not persist files.
# So in production we log to console only.
# In local dev (DEBUG=True), we also log to a local file for debugging.

LOG_DIR = BASE_DIR / "logs"
if DEBUG:
    os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "django.log" if DEBUG else "/dev/null",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"] if not DEBUG else ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "users": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}


# Email configuration
# Defaults to console backend in DEBUG. Configure environment variables for real SMTP in production.
EMAIL_BACKEND = _env('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = _env('EMAIL_HOST', '')
EMAIL_PORT = int(_env('EMAIL_PORT', '587'))
EMAIL_HOST_USER = _env('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = _env('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = _env('EMAIL_USE_SSL', 'False').lower() == 'true'
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', 'AssetMS <no-reply@assetms.local>')

# Custom CSP middleware handles Content Security Policy
# See assetms/middleware.py for CSP configuration
